version: '3.4'

services:
  cozymarinabot:
    image: ${DOCKER_REGISTRY-}cozymarinabot
    build:
      context: .
      dockerfile: CozyMarinaBot/Dockerfile
    env_file:
      'token.env'
    volumes:
      - ./CozyMarinaBot/db:/app/db
